apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistants
  labels:
    {{- include "assistants.labels" . | nindent 4}}
    app.kubernetes.io/component: assistants
spec:
  replicas: {{ .Values.assistants.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: assistants
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: assistants
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: assistants
          image: {{ .Values.assistants.image }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000